# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8caa72fc7febcb75dc3a357172778600f44a03c492edc14894a7864eb2d3b5e06f864ab73e248eece502ca15d7f1c7c1257129b73993a26fb45e7af0c050d3f9

test:
  secret_key_base: d7da416dc47161c9a5304dbf610d92025dc6499e31db5fc63b6e148d7c746af7545a0f1193bba2ad2af80cd502a2de2fc920b8115686de7cf1ab48a9c114c9d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
